#
# Title:      <BASE>
# Author(s):  Malykai
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'wireguard'
        intport: '51820/udp'
        extport: '51820/udp'
        image: 'linuxserver/wireguard'

    - name: Find my public ip
      uri: 
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'false'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/{{pgrole}}:/config'
          - '/lib/modules:/lib/modules'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PEERDNS: 'auto'
          INTERNAL_SUBNET: '10.13.13.0'
          PUID: '1000'
          PGID: '1000'
          TZ: 'America/Chicago'
          SERVERURL: '{{ip_response.content}}'
          SERVERPORT: '51820'
          PEERS: '3'
          PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
          HOME: '/root'
          LANGUAGE: 'en_US.UTF-8'
          LANG: 'en_US.UTF-8'
          TERM: 'xterm'
          DEBIAN_FRONTEND: 'noninteractive'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        restart_policy: unless-stopped
        networks:
          - name: bridge
        state: started
        labels: '{{pg_labels}}'
